# Generated by Django 5.0 on 2024-01-31 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw2_app', '0002_rename_products_order_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='qty',
        ),
    ]
